In [ ]:
#ridge regression project-------------- 4

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#reading an insurance dataset 

In [6]:
df = pd.read_excel("C:\\Users\\Sricharan Reddy\\Downloads\\insurance.xlsx")

In [7]:
df.head()

age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [8]:
df.shape

(1338, 7)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [13]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [15]:
df['children'].describe()

count    1338.000000
mean        1.094918
std         1.205493
min         0.000000
25%         0.000000
50%         1.000000
75%         2.000000
max         5.000000
Name: children, dtype: float64

In [16]:
df['children'].unique()

array([0, 1, 3, 2, 5, 4], dtype=int64)

In [17]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [18]:
df.describe()

age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [19]:
df.corr()

age       bmi  children  expenses
age       1.000000  0.109341  0.042469  0.299008
bmi       0.109341  1.000000  0.012645  0.198576
children  0.042469  0.012645  1.000000  0.067998
expenses  0.299008  0.198576  0.067998  1.000000

In [20]:
#data preprocessing

In [21]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [22]:
#there are no null values in the dataset

In [26]:
df.drop('region',axis = 1,inplace=True)

In [27]:
df.head()

age     sex   bmi  children smoker  expenses
0   19  female  27.9         0    yes  16884.92
1   18    male  33.8         1     no   1725.55
2   28    male  33.0         3     no   4449.46
3   33    male  22.7         0     no  21984.47
4   32    male  28.9         0     no   3866.86

In [28]:
#lets encode the sex and the smoker columns

In [29]:
df['sex'].replace({'male':0,'female':1},inplace=True)

In [30]:
df.head()

age  sex   bmi  children smoker  expenses
0   19    1  27.9         0    yes  16884.92
1   18    0  33.8         1     no   1725.55
2   28    0  33.0         3     no   4449.46
3   33    0  22.7         0     no  21984.47
4   32    0  28.9         0     no   3866.86

In [31]:
df['smoker'].replace({'yes':0,'no':1},inplace=True)

In [32]:
df.head()

age  sex   bmi  children  smoker  expenses
0   19    1  27.9         0       0  16884.92
1   18    0  33.8         1       1   1725.55
2   28    0  33.0         3       1   4449.46
3   33    0  22.7         0       1  21984.47
4   32    0  28.9         0       1   3866.86

In [33]:
x = df.drop('expenses',axis=1)

In [35]:
y = df['expenses']

In [36]:
#modelling 

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state =9)

In [40]:
from sklearn.linear_model import Ridge

In [41]:
model = Ridge()

In [42]:
model.fit(x_train,y_train)

Ridge()

In [43]:
y_pred_train = model.predict(x_train)

In [44]:
y_pred_test = model.predict(x_test)

In [45]:
model.score(x_train,y_train)

0.7432963847740973

In [46]:
model.score(x_test,y_test)

0.7754580997793767

In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
s1 = cross_val_score(model,x,y,cv=5)

In [49]:
print(s1)

[0.76115169 0.70909184 0.77495574 0.73175189 0.75631062]


In [50]:
s1.mean()

0.7466523551462286

In [51]:
#the cross val score looks fine

In [52]:
#prediction on new data

In [65]:
new_data = {
      
    "age" : 20,
    "sex" : 'male',
    "bmi"  : 29,
    "children" : 0,
    "smoker" : 'no' ,
    "region" : 'southeast' 
}


In [66]:
new_data

{'age': 20,
 'sex': 'male',
 'bmi': 29,
 'children': 0,
 'smoker': 'no',
 'region': 'southeast'}

In [67]:
new_data = pd.DataFrame(new_data,index=[0])

In [68]:
new_data

age   sex  bmi  children smoker     region
0   20  male   29         0     no  southeast

In [69]:
new_data.drop("region",axis=1,inplace=True)

In [70]:
new_data

age   sex  bmi  children smoker
0   20  male   29         0     no

In [71]:
new_data['sex'].replace({'male':0,'female':1},inplace=True)

In [72]:
new_data

age  sex  bmi  children smoker
0   20    0   29         0     no

In [73]:
new_data['smoker'].replace({"yes":0,"no":1},inplace=True)

In [74]:
new_data

age  sex  bmi  children  smoker
0   20    0   29         0       1

In [76]:
new_data

age  sex  bmi  children  smoker
0   20    0   29         0       1

In [77]:
model.predict(new_data)

array([2517.01396008])

In [ ]:
#this is how we transform the new input data as we have done during our modelling and we make the new predictions 